version: '3.8'

services:
  redis:
    image: redis:7.4.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    mem_limit: 100m
    command: >
      redis-server
      --maxmemory 100m
volumes:
  redis_data: